package filesystem

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"strings"
	"sync"

	"golang.org/x/sys/unix"
)

const (
	spoolFilePrefix    = ".plain-"
	spoolRandomBytes   = 16
	spoolInodeHeadroom = uint64(16)
)

// Spool is one private, descriptor-confined plaintext staging directory. The
// parent and child directory descriptors remain open so path replacement cannot
// redirect file creation, cleanup, or removal.
type Spool struct {
	path       string
	name       string
	parentFD   int
	fd         int
	removeOnce sync.Once
	removeErr  error
}

// PrepareSpool creates or safely reopens an empty private child beneath a
// trusted existing parent. A child left by an interrupted capture is accepted
// only when it is owned by this process's effective user, has mode 0700, and
// contains only regular files with names generated by this package.
func PrepareSpool(parentPath, childName string) (*Spool, error) {
	if childName == "" || strings.Contains(childName, "/") || childName == "." || childName == ".." {
		return nil, fmt.Errorf("invalid plaintext spool child name")
	}
	parentFD, err := openDirectoryNoSymlinks(parentPath)
	if err != nil {
		return nil, fmt.Errorf("open plaintext spool parent: %w", err)
	}
	closeParent := true
	defer func() {
		if closeParent {
			_ = unix.Close(parentFD)
		}
	}()
	if err := unix.Mkdirat(parentFD, childName, 0o700); err != nil && !errors.Is(err, unix.EEXIST) {
		return nil, fmt.Errorf("create plaintext spool child: %w", err)
	}
	fd, err := unix.Openat(parentFD, childName, unix.O_RDONLY|unix.O_DIRECTORY|unix.O_CLOEXEC|unix.O_NOFOLLOW, 0)
	if err != nil {
		return nil, fmt.Errorf("open plaintext spool child: %w", err)
	}
	closeChild := true
	defer func() {
		if closeChild {
			_ = unix.Close(fd)
		}
	}()
	var stat unix.Stat_t
	if err := unix.Fstat(fd, &stat); err != nil {
		return nil, fmt.Errorf("inspect plaintext spool child: %w", err)
	}
	if stat.Mode&unix.S_IFMT != unix.S_IFDIR || stat.Uid != uint32(os.Geteuid()) || stat.Mode&0o777 != 0o700 {
		return nil, fmt.Errorf("plaintext spool child must be an owned mode-0700 directory")
	}
	spool := &Spool{path: parentPath + string(os.PathSeparator) + childName, name: childName, parentFD: parentFD, fd: fd}
	if err := spool.removeStaleFiles(); err != nil {
		return nil, err
	}
	if err := fsyncFD(parentFD); err != nil {
		return nil, fmt.Errorf("sync plaintext spool parent: %w", err)
	}
	closeParent, closeChild = false, false
	return spool, nil
}

func (spool *Spool) Path() string {
	if spool == nil {
		return ""
	}
	return spool.path
}

// Available reports currently allocatable bytes and free inodes according to
// the filesystem containing the spool.
func (spool *Spool) Available() (uint64, uint64, error) {
	if spool == nil || spool.fd < 0 {
		return 0, 0, fmt.Errorf("plaintext spool is closed")
	}
	return capacityForFD(spool.fd)
}

// DirectoryCapacity reports available bytes and inodes for an existing
// no-symlink directory.
func DirectoryCapacity(path string) (uint64, uint64, error) {
	fd, err := openDirectoryNoSymlinks(path)
	if err != nil {
		return 0, 0, err
	}
	defer unix.Close(fd)
	return capacityForFD(fd)
}

func capacityForFD(fd int) (uint64, uint64, error) {
	var stat unix.Statfs_t
	if err := unix.Fstatfs(fd, &stat); err != nil {
		return 0, 0, fmt.Errorf("inspect filesystem capacity: %w", err)
	}
	if stat.Bsize <= 0 {
		return 0, 0, fmt.Errorf("filesystem reported an invalid block size")
	}
	blockSize := uint64(stat.Bsize)
	blocks := stat.Bavail
	if blocks > ^uint64(0)/blockSize {
		return 0, 0, fmt.Errorf("filesystem capacity is not representable")
	}
	return blocks * blockSize, stat.Ffree, nil
}

// Create reserves capacity for one complete source file before publishing a
// private spool inode. reserveBytes remains free for state and operator safety.
func (spool *Spool) Create(sourcePath string, sourceSize, reserveBytes uint64) (*SpoolFile, error) {
	availableBytes, availableInodes, err := spool.Available()
	if err != nil {
		return nil, err
	}
	if err := checkSpoolCapacity(sourceSize, reserveBytes, availableBytes, availableInodes); err != nil {
		return nil, fmt.Errorf("plaintext spool capacity for %q: %w", sourcePath, err)
	}
	for attempt := 0; attempt < 100; attempt++ {
		var random [spoolRandomBytes]byte
		if _, err := io.ReadFull(rand.Reader, random[:]); err != nil {
			return nil, fmt.Errorf("choose plaintext spool name: %w", err)
		}
		name := spoolFilePrefix + hex.EncodeToString(random[:])
		fd, err := unix.Openat(spool.fd, name, unix.O_RDWR|unix.O_CREAT|unix.O_EXCL|unix.O_CLOEXEC|unix.O_NOFOLLOW, 0o600)
		if errors.Is(err, unix.EEXIST) {
			continue
		}
		if err != nil {
			return nil, fmt.Errorf("create plaintext spool file: %w", err)
		}
		file := os.NewFile(uintptr(fd), name)
		if err := unix.Fchmod(fd, 0o600); err != nil {
			_ = file.Close()
			_ = unix.Unlinkat(spool.fd, name, 0)
			return nil, fmt.Errorf("set plaintext spool mode: %w", err)
		}
		return &SpoolFile{spool: spool, name: name, File: file}, nil
	}
	return nil, fmt.Errorf("could not allocate a unique plaintext spool name")
}

func checkSpoolCapacity(sourceSize, reserveBytes, availableBytes, availableInodes uint64) error {
	if sourceSize > ^uint64(0)-reserveBytes {
		return fmt.Errorf("source size %d plus reserve %d is not representable", sourceSize, reserveBytes)
	}
	required := sourceSize + reserveBytes
	if availableBytes < required {
		return fmt.Errorf("need %d bytes for the source plus %d reserved bytes, but only %d bytes are available", sourceSize, reserveBytes, availableBytes)
	}
	if availableInodes <= spoolInodeHeadroom {
		return fmt.Errorf("need one spool inode while retaining %d free inodes, but only %d are available", spoolInodeHeadroom, availableInodes)
	}
	return nil
}

func (spool *Spool) removeStaleFiles() error {
	copyFD, err := unix.Dup(spool.fd)
	if err != nil {
		return fmt.Errorf("duplicate plaintext spool descriptor: %w", err)
	}
	directory := os.NewFile(uintptr(copyFD), spool.path)
	entries, readErr := directory.ReadDir(-1)
	closeErr := directory.Close()
	if readErr != nil {
		return fmt.Errorf("read plaintext spool: %w", readErr)
	}
	if closeErr != nil {
		return fmt.Errorf("close plaintext spool reader: %w", closeErr)
	}
	for _, entry := range entries {
		name := entry.Name()
		if !validSpoolFilename(name) {
			return fmt.Errorf("unexpected entry %q in plaintext spool", name)
		}
		var stat unix.Stat_t
		if err := unix.Fstatat(spool.fd, name, &stat, unix.AT_SYMLINK_NOFOLLOW); err != nil {
			return fmt.Errorf("inspect stale plaintext spool entry %q: %w", name, err)
		}
		if stat.Mode&unix.S_IFMT != unix.S_IFREG || stat.Uid != uint32(os.Geteuid()) {
			return fmt.Errorf("unexpected type or owner for plaintext spool entry %q", name)
		}
		if err := unix.Unlinkat(spool.fd, name, 0); err != nil {
			return fmt.Errorf("remove stale plaintext spool entry %q: %w", name, err)
		}
	}
	return fsyncFD(spool.fd)
}

func validSpoolFilename(name string) bool {
	if len(name) != len(spoolFilePrefix)+spoolRandomBytes*2 || !strings.HasPrefix(name, spoolFilePrefix) {
		return false
	}
	_, err := hex.DecodeString(strings.TrimPrefix(name, spoolFilePrefix))
	return err == nil
}

// CloseAndRemove removes an empty spool child and closes both retained
// descriptors. Unexpected remaining entries fail closed rather than being
// traversed or recursively deleted.
func (spool *Spool) CloseAndRemove() error {
	if spool == nil {
		return nil
	}
	spool.removeOnce.Do(func() {
		if spool.fd < 0 || spool.parentFD < 0 {
			spool.removeErr = fmt.Errorf("plaintext spool is already closed")
			return
		}
		cleanupErr := spool.removeStaleFiles()
		if cleanupErr == nil {
			if err := unix.Unlinkat(spool.parentFD, spool.name, unix.AT_REMOVEDIR); err != nil {
				cleanupErr = fmt.Errorf("remove plaintext spool child: %w", err)
			} else if err := fsyncFD(spool.parentFD); err != nil {
				cleanupErr = fmt.Errorf("sync plaintext spool parent: %w", err)
			}
		}
		if err := unix.Close(spool.fd); err != nil {
			cleanupErr = errors.Join(cleanupErr, err)
		}
		spool.fd = -1
		if err := unix.Close(spool.parentFD); err != nil {
			cleanupErr = errors.Join(cleanupErr, err)
		}
		spool.parentFD = -1
		spool.removeErr = cleanupErr
	})
	return spool.removeErr
}

// SpoolFile is an open regular plaintext file created beneath a Spool.
type SpoolFile struct {
	spool *Spool
	name  string
	File  *os.File
	once  sync.Once
	err   error
}

func (file *SpoolFile) Sync() error {
	if file == nil || file.File == nil {
		return fmt.Errorf("plaintext spool file is closed")
	}
	return file.File.Sync()
}

// Remove closes and unlinks this exact child through the retained spool
// descriptor, then fsyncs the directory. It is safe to call repeatedly.
func (file *SpoolFile) Remove() error {
	if file == nil {
		return nil
	}
	file.once.Do(func() {
		if file.File != nil {
			if err := file.File.Close(); err != nil {
				file.err = err
			}
			file.File = nil
		}
		if file.spool == nil || file.spool.fd < 0 {
			if file.err == nil {
				file.err = fmt.Errorf("plaintext spool directory is closed")
			}
			return
		}
		if err := unix.Unlinkat(file.spool.fd, file.name, 0); err != nil && !errors.Is(err, unix.ENOENT) && file.err == nil {
			file.err = err
		}
		if err := fsyncFD(file.spool.fd); err != nil && file.err == nil {
			file.err = err
		}
	})
	return file.err
}

func openDirectoryNoSymlinks(path string) (int, error) {
	fd, err := unix.Openat2(unix.AT_FDCWD, path, &unix.OpenHow{
		Flags:   uint64(unix.O_RDONLY | unix.O_DIRECTORY | unix.O_CLOEXEC),
		Resolve: uint64(unix.RESOLVE_NO_SYMLINKS | unix.RESOLVE_NO_MAGICLINKS),
	})
	if errors.Is(err, unix.ENOSYS) {
		return -1, fmt.Errorf("openat2 is required for safe plaintext staging")
	}
	return fd, err
}

func fsyncFD(fd int) error {
	return unix.Fsync(fd)
}
