#!/usr/bin/env bash
set -euo pipefail

while IFS= read -r -d '' entry; do
  name=${entry%%=*}
  case $name in
    AWS_ENDPOINT_URL | AWS_ENDPOINT_URL_*) unset "$name" ;;
  esac
done < <(env -0)

unset BACKUP_DOCKER_TEST BACKUP_AWS_CONTRACT BACKUP_R2_CONTRACT BACKUP_DOCKER_IMAGES_READY BACKUP_GIT_REMOTE_CONTRACT
unset GIT_REMOTE_AWS_PUBLICKEY GIT_REMOTE_AWS_SECRETKEY GIT_REMOTE_AWS_SECRETKEY_FILE GIT_REMOTE_AWS_SECRETKEY_CMD
unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
unset AWS_ACCESS_KEY AWS_SECRET_KEY AWS_SECURITY_TOKEN
unset AWS_PROFILE AWS_DEFAULT_PROFILE AWS_REGION AWS_DEFAULT_REGION AWS_CA_BUNDLE
unset AWS_WEB_IDENTITY_TOKEN_FILE AWS_ROLE_ARN AWS_ROLE_SESSION_NAME
unset AWS_CONTAINER_CREDENTIALS_FULL_URI AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
unset AWS_CONTAINER_AUTHORIZATION_TOKEN AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE
export AWS_CONFIG_FILE=/dev/null
export AWS_SHARED_CREDENTIALS_FILE=/dev/null
export AWS_EC2_METADATA_DISABLED=true
export AWS_IGNORE_CONFIGURED_ENDPOINT_URLS=true
export AWS_USE_FIPS_ENDPOINT=false
export AWS_USE_DUALSTACK_ENDPOINT=false

exec "$@"
